# Generated by Django 5.1.4 on 2025-04-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('imgPath', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('genre', models.JSONField()),
                ('language', models.CharField(max_length=100)),
                ('mpaa_type', models.CharField(max_length=10)),
                ('mpaa_label', models.CharField(max_length=255)),
                ('userRating', models.CharField(max_length=10)),
            ],
        ),
    ]
