# Generated by Django 5.1.4 on 2025-04-10 03:27

from django.db import migrations, models
class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_userrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
